/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokenBuilderRouteImport } from './routes/token-builder'
import { Route as EmailConsoleRouteImport } from './routes/email-console'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TokenBuilderRoute = TokenBuilderRouteImport.update({
  id: '/token-builder',
  path: '/token-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailConsoleRoute = EmailConsoleRouteImport.update({
  id: '/email-console',
  path: '/email-console',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/email-console': typeof EmailConsoleRoute
  '/token-builder': typeof TokenBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/email-console': typeof EmailConsoleRoute
  '/token-builder': typeof TokenBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/email-console': typeof EmailConsoleRoute
  '/token-builder': typeof TokenBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/email-console'
    | '/token-builder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/dashboard' | '/email-console' | '/token-builder'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/email-console'
    | '/token-builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  EmailConsoleRoute: typeof EmailConsoleRoute
  TokenBuilderRoute: typeof TokenBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/token-builder': {
      id: '/token-builder'
      path: '/token-builder'
      fullPath: '/token-builder'
      preLoaderRoute: typeof TokenBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-console': {
      id: '/email-console'
      path: '/email-console'
      fullPath: '/email-console'
      preLoaderRoute: typeof EmailConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  EmailConsoleRoute: EmailConsoleRoute,
  TokenBuilderRoute: TokenBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
